# Site settings
title: "Marionette.js по-русски"
email: instanceofpro@gmail.com
username: instanceofpro
description: "Marionette.js по-русски."
baseurl: /marionettejs.ru
version: 2.2.2

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title
encoding: utf-8
